/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e3e1ec",
        "on-secondary-fixed-variant": "#004395",
        "on-secondary-fixed": "#001a42",
        "on-primary": "#313032",
        "secondary": "#adc6ff",
        "surface-container-low": "#1a1b22",
        "tertiary-fixed-dim": "#cec4c4",
        "surface-container-highest": "#33343c",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#d8e2ff",
        "inverse-on-surface": "#2f3038",
        "surface-dim": "#12131a",
        "secondary-fixed-dim": "#adc6ff",
        "surface-bright": "#383941",
        "surface-tint": "#c8c6c8",
        "outline-variant": "#47464a",
        "secondary-container": "#0566d9",
        "on-tertiary-fixed-variant": "#4c4545",
        "on-error": "#690005",
        "tertiary": "#cec4c4",
        "inverse-surface": "#e3e1ec",
        "inverse-primary": "#5f5e60",
        "surface-container": "#1e1f26",
        "on-primary-container": "#7a787b",
        "error": "#ffb4ab",
        "on-primary-fixed": "#1c1b1d",
        "surface-container-high": "#292931",
        "on-secondary": "#002e6a",
        "surface": "#12131a",
        "on-tertiary-fixed": "#1f1a1a",
        "on-surface-variant": "#c8c5ca",
        "outline": "#919095",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#474649",
        "on-secondary-container": "#e6ecff",
        "on-tertiary-container": "#7f7777",
        "surface-variant": "#33343c",
        "on-tertiary": "#352f2f",
        "on-background": "#e3e1ec",
        "primary-container": "#09090b",
        "surface-container-lowest": "#0d0e15",
        "primary": "#c8c6c8",
        "primary-fixed-dim": "#c8c6c8",
        "background": "#12131a",
        "tertiary-container": "#0c0808",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Geist", "sans-serif"],
      },
    },
  },
  plugins: [],
};
